name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/shared/requirements.txt
    
    - name: Run web app tests
      run: |
        cd src/web
        python -c "import app; print('Web app imports successfully')"
    
    - name: Check CLI version
      run: |
        cd src/shared
        python -c "import menu2img; print('CLI version imports successfully')"

  test-desktop:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check desktop app structure
      run: |
        test -f src/desktop/main.js
        test -f src/desktop/preload.js
        test -f src/desktop/renderer.js
        echo "Desktop app files exist"

  build-desktop:
    runs-on: ubuntu-latest
    needs: [test-web, test-desktop]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build desktop app
      run: npm run build 